name: apn_http
description: An Appnormal package centered around providing tools for setting up http server calls.
version: 1.0.0
homepage: https://appnormal.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  apn_state: ^1.2.6
  json_annotation: ^3.0.1
  dio: ^3.0.1
  dio_flutter_transformer: ^3.0.2
  dio_http_cache: ^0.2.8
  pretty_dio_logger: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0 