name: apn_http
description: An Appnormal package centered around providing tools for setting up http server calls.
version: 2.0.0-nullsafety-3
homepage: https://appnormal.com

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  apn_state: ^2.0.1
  dio: ^4.0.0-prev1
  pretty_dio_logger: ^1.2.0-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
